version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: trackup-mysql
    restart: always
    environment:
      MYSQL_DATABASE: trackup_db
      MYSQL_USER: alvaro
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: